export const lightTheme = {
    bg:"#e7e7e7",
    sidebar:"#f5f5f5",
    sidebarBorder:"#ececec",
    sidebarHoverBG:"#e0e0e0",
    sidebarHoverText:"#5f6f89",
    headerBG:"#85bfd0",
    headerBorder:"#dbdbdb",
    submitButtonBG :"#e5e5e5",
    submitButtonHoverBG:"#85bfd0",
    submitTextHover:"#45717d",
    submitBorder:"#e3e3e3",
    confessionBG:"#f5f5f5",
    confessionBorder:"#dbdbdb",
    confessionTitle:"#4a5465",
    switchTextColor: "#323842",
    switchOnColor:"#84bcd4",
    footerBG:"#efefef",
    footerBorder:"#dbdbdb",
    labelColor:"#61727f",
    textBoxBorder:"#c7c7c7",
}